#!/bin/sh
#$ -cwd
#$ -V -S /bin/bash
####$ -V -S /bin/zsh
#$ -N TiNiAl_CrySPY_ID
#$ -pe smp 2
####$ -q ibis1.q
####$ -q ibis2.q


# ---------- OpenMP
export OMP_NUM_THREADS=2

# ---------- ASE
/usr/local/Python-3.10.13/bin/python3 chgnet_in.py > out.log

# ---------- for error --> skip
#if [ ! -f "log.tote" ]; then
#    sed -i -e '3 s/^.*$/skip/' stat_job
#    exit 1
#fi

# --------- CrySPY
sed -i -e '3 s/^.*$/done/' stat_job
