#!/bin/sh

# ---------- OpenMP
export OMP_NUM_THREADS=1

# ---------- ASE
python3 ase_in.py > out.log

# ---------- qe if crash
if [ -e "CRASH" ]; then
    sed -i -e '3 s/^.*$/skip/' stat_job
    exit 1
fi

# ---------- for error --> skip
if [ ! -f "log.tote" ]; then
    sed -i -e '3 s/^.*$/skip/' stat_job
    exit 1
fi

