#!/bin/sh
#$ -cwd
#$ -V -S /bin/bash
####$ -V -S /bin/zsh
#$ -N Si8_CrySPY_ID
#$ -pe smp 20
####$ -q ibis1.q
####$ -q ibis2.q


# ---------- OpenMP
export OMP_NUM_THREADS=1

# ---------- OpenMPI
export NSLOTS=4

# ---------- qe run
mpirun -np $NSLOTS pw.x < pwscf.in > pwscf.out

# ---------- skip
if [ -e "CRASH" ]; then
    sed -i -e '3 s/^.*$/skip/' stat_job
    exit 1
fi
